### ISSUE TITLE
warning C"8032: An instance of analyzer ConfigureAwaitChecker.Analyzer.ConfigureAwaitCheckerAnalyzer cannot be created...

### ISSUE THREAD

**Issue by alphaleonis** [cincuranet/ConfigureAwaitChecker#2] opened 2015-11-26 13:54 UTC
When building a project using Visual Studio 2015 I get the following warning after installing this analyzer as a nuget package:

```
1>CSC : warning CS8032: An instance of analyzer ConfigureAwaitChecker.Analyzer.ConfigureAwaitCheckerAnalyzer cannot be created from D:\My Documents\Visual Studio 2015\Projects\ConsoleApplication23\packages\ConfigureAwaitChecker.Analyzer.1.0.0-beta3\analyzers\dotnet\cs\ConfigureAwaitChecker.dll : Method 'get_SupportedDiagnostics' in type 'ConfigureAwaitChecker.Analyzer.ConfigureAwaitCheckerAnalyzer' from assembly 'ConfigureAwaitChecker, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation..
```

Any ideas?

**Comment by cincuranet** [comment] 2015-11-26 14:57
Not from top of my head. Maybe it's related to #1. The types might not be matching. I'll have a look.

**Comment by alphaleonis** [comment] 2015-11-26 15:04
I managed to fix it by basically copying the project file and packages.config from a new Analyzer project in Visual Studio. So probably there is some version conflict between the referenced assemblies and what Visual Studio uses... or something.... not quite sure.   But this probably meant "downgrading" some packages.

**Comment by cincuranet** [comment] 2015-11-28 04:57
Duplicate of #1.

**Closed as completed by cincuranet** 2015-11-28 04:57 UTC
